#!/usr/bin/env python3
"""Builds crates/core/src/constituencies.rs: every assembly constituency with its Malayalam name and district.

Names and districts come from a saved copy of the KIIFB dashboard page (its MLA links carry the
Malayalam names). Where KIIFB gives no Malayalam name, the one in BY_HAND is used.
Usage: scripts/constituencies.py saved-gis-page.html
"""
import collections, json, pathlib, re, sys

# KIIFB's spelling -> the one spelling we show.
RENAME = {"Vypeen": "Vypin"}
BY_HAND = {
    "Ambalappuzha": "അമ്പലപ്പുഴ", "Chalakudy": "ചാലക്കുടി", "Chathannoor": "ചാത്തന്നൂർ", "Ernad": "ഏറനാട്",
    "Irinjalakuda": "ഇരിങ്ങാലക്കുട", "Karunagapally": "കരുനാഗപ്പള്ളി", "Kazhakoottam": "കഴക്കൂട്ടം", "Koyilandy": "കൊയിലാണ്ടി",
    "Kozhikode North": "കോഴിക്കോട് നോർത്ത്", "Kozhikode South": "കോഴിക്കോട് സൗത്ത്", "Kunnathunad": "കുന്നത്തുനാട്",
    "Kuttiady": "കുറ്റ്യാടി", "Mannarkkad": "മണ്ണാർക്കാട്", "Mavelikkara": "മാവേലിക്കര", "Nemmara": "നെന്മാറ", "Ottappalam": "ഒറ്റപ്പാലം",
    "Sulthanbathery": "സുൽത്താൻ ബത്തേരി", "Udma": "ഉദുമ", "Vallikunnu": "വള്ളിക്കുന്ന്", "Vatakara": "വടകര", "Wandoor": "വണ്ടൂർ",
    # Spellings already in use on the site.
    "Kalamassery": "കളമശ്ശേരി", "Thripunithura": "തൃപ്പൂണിത്തുറ", "Vypin": "വൈപ്പിൻ",
}

page = open(sys.argv[1], encoding="utf-8", errors="replace").read()
start = page.index("=", page.index("const MARKERS")) + 1
markers = json.JSONDecoder().raw_decode(page[start:].lstrip())[0]

def bare(name):
    return re.sub(r"\s*\(.*", "", name.replace("\xa0", " ")).strip()

malayalam = collections.defaultdict(collections.Counter)
district = collections.defaultdict(collections.Counter)
for m in markers:
    if not m.get("c"):
        continue
    name = bare(m["c"])
    name = RENAME.get(name, name)
    district[name][m["d"]] += 1
    link = m.get("link")
    if isinstance(link, dict) and link.get("മണ്ഡലം"):
        malayalam[name][bare(link["മണ്ഡലം"])] += 1

rows = []
for name in sorted(district):
    ml = BY_HAND.get(name) or (malayalam[name].most_common(1)[0][0] if malayalam[name] else None)
    if not ml:
        sys.exit(f"no Malayalam name for {name}; add it to BY_HAND")
    rows.append((name, ml, district[name].most_common(1)[0][0]))

lines = [
    "//! Kerala's assembly constituencies: name, Malayalam name, district. Generated by scripts/constituencies.py",
    "//! from the KIIFB dashboard's own listing; sorted by name.",
    "",
    "pub const CONSTITUENCIES: &[(&str, &str, &str)] = &[",
]
lines += [f'    ("{n}", "{ml}", "{d}"),' for n, ml, d in rows]
lines += ["];", ""]
out = pathlib.Path(__file__).resolve().parent.parent / "crates/core/src/constituencies.rs"
out.write_text("\n".join(lines))
print(f"{len(rows)} constituencies")
