#!/usr/bin/env python3
"""Builds crates/worker/src/district.rs: a simplified outline of the pilot district.

The boundary comes from OpenStreetMap (ODbL) through Nominatim. Run once; the output is committed.
Usage: scripts/district.py [cached-nominatim.json]
"""
import json, math, sys, urllib.request, pathlib

QUERY = "https://nominatim.openstreetmap.org/search?q=Ernakulam+district,+Kerala,+India&format=jsonv2&polygon_geojson=1&limit=1"
TOLERANCE = 0.004  # degrees, roughly 400 m
WIDTH = 320.0
PAD = 6.0

def fetch():
    if len(sys.argv) > 1:
        return json.load(open(sys.argv[1]))
    req = urllib.request.Request(QUERY, headers={"User-Agent": "KanakkuBuild/0.1 (one-off boundary fetch)"})
    return json.load(urllib.request.urlopen(req))

def simplify(points, tol):
    """Douglas-Peucker."""
    if len(points) < 3:
        return points
    (x1, y1), (x2, y2) = points[0], points[-1]
    dx, dy = x2 - x1, y2 - y1
    norm = math.hypot(dx, dy) or 1e-12
    dist, index = max((abs(dy * (x - x1) - dx * (y - y1)) / norm, i) for i, (x, y) in enumerate(points[1:-1], 1))
    if dist <= tol:
        return [points[0], points[-1]]
    return simplify(points[: index + 1], tol)[:-1] + simplify(points[index:], tol)

place = fetch()[0]
geo = place["geojson"]
polys = geo["coordinates"] if geo["type"] == "MultiPolygon" else [geo["coordinates"]]
ring = max((poly[0] for poly in polys), key=len)
half = len(ring) // 2
outline = simplify(ring[: half + 1], TOLERANCE)[:-1] + simplify(ring[half:], TOLERANCE)

lngs, lats = [p[0] for p in ring], [p[1] for p in ring]
min_lng, max_lng, min_lat, max_lat = min(lngs), max(lngs), min(lats), max(lats)
cos = math.cos(math.radians((min_lat + max_lat) / 2))
k = (WIDTH - 2 * PAD) / ((max_lng - min_lng) * cos)
height = (max_lat - min_lat) * k + 2 * PAD

def project(lng, lat):
    return (PAD + (lng - min_lng) * cos * k, PAD + (max_lat - lat) * k)

path = "M" + "L".join(f"{x:.1f} {y:.1f}" for x, y in (project(*p[:2]) for p in outline)) + "Z"
out = pathlib.Path(__file__).resolve().parent.parent / "crates/worker/src/district.rs"
out.write_text(f'''//! Outline of Ernakulam district for the small maps. Generated by scripts/district.py.
//! Boundary © OpenStreetMap contributors (ODbL), relation {place.get("osm_id")}, simplified to {len(outline)} points.

pub const WIDTH: f64 = {WIDTH:.1f};
pub const HEIGHT: f64 = {height:.1f};

const MIN_LNG: f64 = {min_lng:.6f};
const MAX_LAT: f64 = {max_lat:.6f};
const PAD: f64 = {PAD:.1f};
const KX: f64 = {cos * k:.4f};
const KY: f64 = {k:.4f};

/// SVG path of the district boundary in the `WIDTH` x `HEIGHT` box.
pub const OUTLINE: &str = "{path}";

/// Where a coordinate falls in the box, or `None` when it lies outside it.
pub fn project(lat: f64, lng: f64) -> Option<(f64, f64)> {{
    let x = PAD + (lng - MIN_LNG) * KX;
    let y = PAD + (MAX_LAT - lat) * KY;
    ((0.0..=WIDTH).contains(&x) && (0.0..=HEIGHT).contains(&y)).then_some((x, y))
}}
''')
print(f"{len(ring)} points simplified to {len(outline)}; box {WIDTH:.0f} x {height:.0f}; path {len(path)} chars")
