#!/usr/bin/env python3
"""Builds crates/worker/src/district.rs: simplified outlines of Kerala's 14 districts.

Each district is drawn twice: in its own box, for a district's page, and in one box for the
whole state. Boundaries come from OpenStreetMap (ODbL) through Nominatim, one request a second.
Run once; the output is committed.
Usage: scripts/districts.py [cache-directory]
"""
import json, math, pathlib, sys, time, urllib.parse, urllib.request

DISTRICTS = ["Thiruvananthapuram", "Kollam", "Pathanamthitta", "Alappuzha", "Kottayam", "Idukki", "Ernakulam",
             "Thrissur", "Palakkad", "Malappuram", "Kozhikode", "Wayanad", "Kannur", "Kasaragod"]
OWN_TOLERANCE = 0.004    # degrees, roughly 400 m
STATE_TOLERANCE = 0.012
OWN_WIDTH = 320.0
STATE_WIDTH = 260.0
PAD = 6.0

cache = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else None

def fetch(name):
    saved = cache / f"{name}.json" if cache else None
    if saved and saved.exists():
        return json.loads(saved.read_text())
    query = urllib.parse.urlencode({"q": f"{name} district, Kerala, India", "format": "jsonv2", "polygon_geojson": 1, "limit": 1})
    req = urllib.request.Request(f"https://nominatim.openstreetmap.org/search?{query}",
                                 headers={"User-Agent": "KanakkuBuild/0.1 (one-off boundary fetch)"})
    place = json.load(urllib.request.urlopen(req))[0]
    if saved:
        saved.write_text(json.dumps(place))
    time.sleep(1.1)
    return place

def simplify(points, tol):
    """Douglas-Peucker."""
    if len(points) < 3:
        return points
    (x1, y1), (x2, y2) = points[0], points[-1]
    dx, dy = x2 - x1, y2 - y1
    norm = math.hypot(dx, dy) or 1e-12
    dist, index = max((abs(dy * (x - x1) - dx * (y - y1)) / norm, i) for i, (x, y) in enumerate(points[1:-1], 1))
    if dist <= tol:
        return [points[0], points[-1]]
    return simplify(points[: index + 1], tol)[:-1] + simplify(points[index:], tol)

def closed(ring, tol):
    half = len(ring) // 2
    return simplify(ring[: half + 1], tol)[:-1] + simplify(ring[half:], tol)

def frame(rings, width):
    lngs = [p[0] for ring in rings for p in ring]
    lats = [p[1] for ring in rings for p in ring]
    min_lng, max_lng, min_lat, max_lat = min(lngs), max(lngs), min(lats), max(lats)
    cos = math.cos(math.radians((min_lat + max_lat) / 2))
    k = (width - 2 * PAD) / ((max_lng - min_lng) * cos)
    return {"width": width, "height": (max_lat - min_lat) * k + 2 * PAD, "min_lng": min_lng, "max_lat": max_lat, "kx": cos * k, "ky": k}

def path(ring, f):
    points = ((PAD + (lng - f["min_lng"]) * f["kx"], PAD + (f["max_lat"] - lat) * f["ky"]) for lng, lat in ring)
    return "M" + "L".join(f"{x:.1f} {y:.1f}" for x, y in points) + "Z"

def rust_frame(f):
    return (f'Frame {{ width: {f["width"]:.1f}, height: {f["height"]:.1f}, min_lng: {f["min_lng"]:.6f}, '
            f'max_lat: {f["max_lat"]:.6f}, kx: {f["kx"]:.4f}, ky: {f["ky"]:.4f} }}')

rings, ids = {}, {}
for name in DISTRICTS:
    place = fetch(name)
    geo = place["geojson"]
    polys = geo["coordinates"] if geo["type"] == "MultiPolygon" else [geo["coordinates"]]
    rings[name] = [p[:2] for p in max((poly[0] for poly in polys), key=len)]
    ids[name] = place.get("osm_id")

state = frame(rings.values(), STATE_WIDTH)
entries = []
for name in DISTRICTS:
    own = frame([rings[name]], OWN_WIDTH)
    entries.append(
        f'    District {{\n        name: "{name}",\n        frame: {rust_frame(own)},\n'
        f'        outline: "{path(closed(rings[name], OWN_TOLERANCE), own)}",\n'
        f'        in_state: "{path(closed(rings[name], STATE_TOLERANCE), state)}",\n    }},'
    )

out = pathlib.Path(__file__).resolve().parent.parent / "crates/worker/src/district.rs"
out.write_text(f'''//! Outlines of Kerala's districts for the small maps. Generated by scripts/districts.py.
//! Boundaries © OpenStreetMap contributors (ODbL), simplified. Relations: {", ".join(str(ids[n]) for n in DISTRICTS)}.

const PAD: f64 = {PAD:.1f};

/// A box that a piece of the map is drawn in, and how coordinates fall into it.
pub struct Frame {{
    pub width: f64,
    pub height: f64,
    min_lng: f64,
    max_lat: f64,
    kx: f64,
    ky: f64,
}}

impl Frame {{
    /// Where a coordinate falls in the box, or `None` when it lies outside it.
    pub fn project(&self, lat: f64, lng: f64) -> Option<(f64, f64)> {{
        let x = PAD + (lng - self.min_lng) * self.kx;
        let y = PAD + (self.max_lat - lat) * self.ky;
        ((0.0..=self.width).contains(&x) && (0.0..=self.height).contains(&y)).then_some((x, y))
    }}
}}

pub struct District {{
    pub name: &'static str,
    /// The district's own box.
    pub frame: Frame,
    /// SVG path of the boundary in its own box.
    pub outline: &'static str,
    /// SVG path of the boundary in the state's box.
    pub in_state: &'static str,
}}

/// The box the whole state is drawn in.
pub const STATE: Frame = {rust_frame(state)};

pub const DISTRICTS: [District; {len(DISTRICTS)}] = [
{chr(10).join(entries)}
];

pub fn get(name: &str) -> Option<&'static District> {{
    DISTRICTS.iter().find(|d| d.name == name)
}}
''')
print(f"{len(DISTRICTS)} districts; state box {state['width']:.0f} x {state['height']:.0f}; file {out.stat().st_size} bytes")
