#!/usr/bin/env python3
"""Builds crates/worker/src/icons.rs from Lucide (ISC licence, node_modules/lucide-static).

Only the icons named here are embedded. Run after changing the list; the output is committed.
"""
import re, pathlib

ICONS = [
    # interface
    "search", "sliders-horizontal", "map-pin", "flag", "arrow-right", "arrow-left", "arrow-up-right", "download", "share-2", "x",
    "database", "scale", "chevron-right", "languages", "landmark", "circle-help",
    # departments
    "graduation-cap", "school", "route", "heart-pulse", "droplets", "cpu", "ship", "fish", "users", "building-2", "stamp",
    "zap", "trophy", "sprout", "trees", "bus", "factory", "palmtree", "shield", "drama",
]

root = pathlib.Path(__file__).resolve().parent.parent
src = root / "node_modules/lucide-static/icons"
lines = [
    "//! Icons from Lucide (https://lucide.dev, ISC licence). Generated by scripts/icons.py.",
    "//! Each constant is the inner markup of a 24x24 stroke icon.",
    "",
]
for name in ICONS:
    svg = (src / f"{name}.svg").read_text()
    inner = re.search(r"<svg[^>]*>(.*)</svg>", svg, re.S).group(1)
    inner = re.sub(r"\s+", " ", inner).replace("> <", "><").strip()
    const = name.upper().replace("-", "_")
    lines.append(f'pub const {const}: &str = r#"{inner}"#;')
(root / "crates/worker/src/icons.rs").write_text("\n".join(lines) + "\n")
print(f"{len(ICONS)} icons")
